const patologias = [
  "ulcera.gltf",
  "quinto_varo_incipiente.gltf",
  "pie_plano.gltf",
  "pie_cavo.gltf",
  "onicomicosis.gltf",
  "onicogrifosis.gltf",
  "onicofosis.gltf",
  "onicocriptosis.gltf",
  "hiperqueratosis.gltf",
  "heloma_vascular.gltf",
  "heloma_septico.gltf",
  "heloma_neurovascular.gltf",
  "heloma_miliar.gltf",
  "heloma_interdigital_interno.gltf",
  "heloma_interdigital_externo.gltf",
  "heloma_fisurado.gltf",
  "heloma_helosis.gltf",
  "heloma_blando.gltf",
  "heloma.gltf",
  "hallux_valgus_incipiente.gltf",
  "dedo_martillo.gltf",
  "dedo_garra_total.gltf",
  "dedo_garra_invertido.gltf",
  "dedo_garra.gltf",
  "dedo_acabalgado.gltf",
  "hematoma.gltf",
  "herida.gltf",
  "paciente_diabetico.gltf",
  "una_involuta.gltf",
  "onicocauxis.gltf",
  "hallux_valgus_pronunciado.gltf",
  "verruga.gltf",
];

export default patologias;
